### PR TITLE
Hotfix: remove all traces

### PR DESCRIPTION
**Pull request by danielbeardsley**
We stopped using this years ago, let's not bother maintaining it.
It once was useful and it no longer is (to us).

This was a parallel program to 'feature' but it branched off and
merged into *stable* instead of *master*.

We don't maintain a stable branch anymore and just always deploy
master, so let's not keep this vestigal stuff around.

### CODE REVIEW

**Comment by sctice** [comment]
I was confused by the pull title because I initially interpreted it as communicating that this pull is itself a "hotfix", and then I was asking myself: "remove all traces of _what_?"

CR 🎏

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by k0rvusk0r4x** [comment]
1. `git pull`ed on this repo to bring my copy up to date with current master.
2. `gg`ed 'hotfix' to note all the places it showed up.
3. Checked out this branch.
4. `gg`ed 'hotfix' again and noted it is now in one comment in `README.md` to clarify that it does not exist.
5. Checked the comments that were modified, and noted they work grammatically and make sense.

QA 😺

**Comment by kwiens** [comment]
This has no CI so it's deploy blocked, but I think this is ready to merge?

**Comment by danielbeardsley** [comment]
For QAing, I'll build this and install it in our dev environment.

**Comment by danielbeardsley** [comment]
I merged master, made a build, installed it in our dev environment and it still did the basics.

QA 👍

**Pull request merged**
