### PR TITLE
feature-clean: remove it

### PR DESCRIPTION
**Pull request by danielbeardsley**
It already caused loss-of-data for me.

Did we really make `feature clean` a *short-cut* for `git clean -ffd`
cause that seems kinda silly.

### CODE REVIEW

**Comment by kwiens** [comment]
Can we please either merge this or close it?

**Comment by danielbeardsley** [comment]
Have any @iFixit/coders used this feature recently? I want to drop it.

**Comment by davidrans** [comment]
I don't use it

**Comment by copperwall** [comment]
I don't use it.

**Comment by timothyasp** [comment]
dont use

**Pull request merged**
