### PR TITLE
Feature Finsh: No hard line wraps

### PR DESCRIPTION
**Pull request by evannoronha**
Summary
---

The forced line wrapping in feature finish is annoying. The resulting text looks pretty bad in the GH UI, which is where it's ultimately read and edited.

QA
---
I don't know how `feature` is built and deployed on cominor. QA instructions incoming...

### CODE REVIEW

**Comment by jarstelfox** [comment]
CR 🌵 but I have to say feature start hasn't worked for me for a year+, I'm not sure feature is worth maintaining long term

**Comment by evannoronha** [comment]
> I have to say feature start hasn't worked for me for a year+

Hrm. I think it works for most folks. Albeit with a ton of warnings.

**Comment by danielbeardsley** [comment]
> The forced line wrapping in feature finish is annoying. The resulting text looks pretty bad in the GH UI, which is where it's ultimately read and edited.

Huh...  I feel the opposite (I've liked the wrapping). And I think it looks great in the GUI, while I don't like the look of super-long-lines. Though let me review some recent pulls.....

I guess I think of it as writing a commit message to sum up the whole pull request and thus I want to format it just like I do my commit messages: pull title, blank line, 72-char-wrapped body. Though.. now I realize we haven't been putting pull descriptions in the merge commits for a long time, so how it looks as a git commit is irrelevant.

Here's an example:
With wrapping:
image

Without:
image

I think I really like the wrapping still, I much prefer shorter lines. *But* it's just a preference and there are other ways to go about that...  I could probably find a way to use custom css and bump the font-size of pull descriptions. Or set a max-width on the container. Ok, I'm inspired!

CR :+1:

**Comment by danielbeardsley** [comment]
> but I have to say feature start hasn't worked for me for a year+

Maybe it's fixed?

Seems to work fine as your user from your code dir :shrug: 

image

**Comment by jarstelfox** [comment]
Ah sorry I guess what I meant is I don’t use feature start since feature finish crashes usually due to code surrounding the issue number

**Comment by evannoronha** [comment]
I pointed my $PATH at this branch of git-scripts and `feature finish`d. There is now no longer text wrapping.

QA 🔥

**Pull request merged**
